default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: portfolio_backend_production
  username: portfolio_backend
  password: <%= ENV["PORTFOLIO_BACKEND_DATABASE_PASSWORD"] %>
  # Other production-specific configuration options can be added here.
